export const CODE_PREFIX_WARNING = 'W';

export enum PERIOD_WARNING_TYPE_ENUM {
  PERIOD_WARNING_DEVICE = 1,
  PERIOD_WARNING_SUPPLY = 2,
  PERIOD_WARNING_REPLACE_ACCESSORY = 3,
  PERIOD_WARNING_DEVICE_ERROR = 4,
  PERIOD_WARNING_SUPPLY_ERROR = 5,
}

export enum PERIOD_WARNING_PRIORITY_ENUM {
  MAJOR = 1,
  BLOCKER = 2,
}

export enum WARNING_STATUS_ENUM {
  CREATED = 1,
  CONFIRMED = 2,
  REJECTED = 3,
  IN_PROGRESS = 4,
  COMPLETED = 5,
}

export const STATUS_TO_REJECT_WARNING: number[] = [WARNING_STATUS_ENUM.CREATED];

export const WARNING_CODE_CONST = {
  MAX_LENGTH: 12,
  COLUMN: 'code',
  PAD_CHAR: '0',
  DEFAULT_CODE: '0',
};

export const WARNING_CODE_PREFIX = 'W';

export const WARNING_TYPE_ENUM = {
  USER_REQUEST: 1,
  PERIOD_MANTANCE: 2,
  WARNING: 3,
  CHECKLIST_TEMPLATE: 4,
};
