version: "2.0"
services:
  registry:
    image: registry:2.7
    ports:
      - "${REGISTRY_PORT}:5000"
    environment:
      - REGISTRY_PORT=${REGISTRY_PORT}
      - REGISTRY_UI_PORT=${REGISTRY_UI_PORT}
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry-config/htpasswd:/etc/docker/registry/htpasswd

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "${REGISTRY_UI_PORT}:80"
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://localhost:${REGISTRY_PORT}
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
