# docker compose version
version: '3.7'
# all the containers have to declare inside services
services:
  sample-service1a:
    container_name: sample-service-a
    image: sample-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mesx-net
    ports:
      - ${SERVICE_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  migration:
    image: sample-service:1.0.0
    env_file:
      - .env
    command: npm run migrate:run
    depends_on:
      - postgres
    networks:
      - mesx-net
    # postgres
  postgres:
    container_name: sample-service1a-db
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_CONTAINER_PORT}:${DATABASE_PORT}
    networks:
      - mesx-net
    restart: unless-stopped
networks:
  mesx-net:
    external: true

# save (persist) data
volumes:
  db_data: {}
