export enum PERIOD_WARNING_STATUS_ENUM {
  CREATED = 1,
  CONFIRMED = 2,
  REJECTED = 3,
}

export const STATUS_TO_APPROVE_PERIOD_WARNING: number[] = [
  PERIOD_WARNING_STATUS_ENUM.CREATED,
];

export enum PERIOD_WARNING_PRIORITY_ENUM {
  MAJOR = 1,
  BLOCKER = 2,
}

export enum PERIOD_WARNING_TYPE_ENUM {
  PERIOD_WARNING_DEVICE = 1,
  PERIOD_WARNING_SUPPLY = 2,
  PERIOD_WARNING_REPLACE_ACCESSORY = 3,
  PERIOD_WARNING_DEVICE_ERROR = 4,
  PERIOD_WARNING_SUPPLY_ERROR = 5,
}
