#!/bin/bash

echo REACT_APP_HOST=$REACT_APP_HOST >> .env
echo REACT_APP_SOCKET_HOST=$REACT_APP_SOCKET_HOST >> .env
echo NODE_ENV=$NODE_ENV >> .env
echo SERVER_TIMEOUT=$SERVER_TIMEOUT >> .env
echo SERVER_PORT=$SERVER_DEMO_PORT >> .env

echo DATABASE_HOST=$DATABASE_DEMO_HOST >> .env
echo DATABASE_TYPE=postgres >> .env
echo DATABASE_PORT=$DATABASE_DEMO_PORT >> .env
echo DATABASE_USERNAME=$DATABASE_DEMO_USERNAME >> .env
echo DATABASE_PASSWORD=$DATABASE_DEMO_PASSWORD >> .env
echo DATABASE_NAME=$DATABASE_DEMO_NAME >> .env
echo DATABASE_CONNECTION_TIME_OUT=150000 >> .env
echo DATABASE_ACQUIRE_TIME_OUT=150000 >> .env
echo DATABASE_CONNECTION_LIMIT=20 >> .env

echo USER_SERVICE_PORT=$USER_SERVICE_DEMO_PORT >> .env
echo USER_SERVICE_HOST=$USER_SERVICE_DEMO_HOST >> .env

echo WAREHOUSE_SERVICE_PORT=$WAREHOUSE_SERVICE_DEMO_PORT >> .env
echo WAREHOUSE_SERVICE_HOST=$WAREHOUSE_SERVICE_DEMO_HOST >> .env

echo ITEM_SERVICE_PORT=$ITEM_SERVICE_DEMO_PORT >> .env
echo ITEM_SERVICE_HOST=$ITEM_SERVICE_DEMO_HOST >> .env

echo SALE_SERVICE_PORT=$SALE_SERVICE_DEMO_PORT >> .env
echo SALE_SERVICE_HOST=$SALE_SERVICE_DEMO_HOST >> .env

echo PRODUCE_SERVICE_PORT=$PRODUCE_SERVICE_DEMO_PORT >> .env
echo PRODUCE_SERVICE_HOST=$PRODUCE_SERVICE_DEMO_HOST >> .env


echo CORS_ORIGINS=* >> .env