export const DEPARTMENT_PERMISSION_SETTING = {
  WAREHOUSE: 1,
  PRODUCTION: 2,
  QC: 3,
  IT: 4,
  SALE: 5,
  ADMIN: 6,
};

export const DEPARTMENT_PERMISSION_SETTING_CAN_SEE = [
  DEPARTMENT_PERMISSION_SETTING.IT,
  DEPARTMENT_PERMISSION_SETTING.ADMIN,
];
