import { WARNING } from "@nestcloud/common";
import { DEFECT_GROUP_PERMISSION, DEFECT_PERMISSION } from "./defect";
import { DEVICE_GROUP_PERMISSION2, DEVICE_PERMISSION } from "./device";
import { DEVICE_ASSIGNMENT_GROUP_PERMISSION, DEVICE_ASSIGNMENT_PERMISSION } from "./device-assignment";
import { DEVICE_GROUP_GROUP_PERMISSION, DEVICE_GROUP_PERMISSION } from "./device-group";
import { DEVICE_REQUEST_GROUP_PERMISSION, DEVICE_REQUEST_PERMISSION } from "./device-request";
import { JOB_GROUP_PERMISSION, JOB_PERMISSION } from "./job";
import { MAINTAIN_REQUEST_GROUP_PERMISSION, MAINTAIN_REQUEST_PERMISSION } from "./maintain-request";
import { MAINTENANCE_ATTRIBUTE_GROUP_PERMISSION, MAINTENANCE_ATTRIBUTE_PERMISSION } from "./maintenance-attribute";
import { MAINTENANCE_TEAM_GROUP_PERMISSION, MAINTENANCE_TEAM_PERMISSION } from "./maintenance-team";
import { PLAN_GROUP_PERMISSION, PLAN_PERMISSION } from "./plan";
import { DEVICE_STATUS_GROUP_PERMISSION, DEVICE_STATUS_PERMISSION } from "./report-device-status";
import { SUPPLY_GROUP_PERMISSION2, SUPPLY_PERMISSION } from "./supply";
import { SUPPLY_GROUP_GROUP_PERMISSION, SUPPLY_GROUP_PERMISSION } from "./supply-group";
import { WARNING_GROUP_PERMISSION, WARNING_PERMISSION } from "./warning";

export const PERMISSION = [
  ...DEFECT_PERMISSION,
  ...DEVICE_ASSIGNMENT_PERMISSION,
  ...DEVICE_GROUP_PERMISSION,
  ...DEVICE_REQUEST_PERMISSION,
  ...DEVICE_PERMISSION,
  ...JOB_PERMISSION,
  ...MAINTAIN_REQUEST_PERMISSION,
  ...MAINTENANCE_ATTRIBUTE_PERMISSION,
  ...MAINTENANCE_TEAM_PERMISSION,
  ...PLAN_PERMISSION,
  ...DEVICE_STATUS_PERMISSION,
  ...SUPPLY_GROUP_PERMISSION,
  ...SUPPLY_PERMISSION,
  ...WARNING_PERMISSION
]

export const GROUP_PERMISSION = [
  DEFECT_GROUP_PERMISSION,
  DEVICE_ASSIGNMENT_GROUP_PERMISSION,
  DEVICE_GROUP_GROUP_PERMISSION,
  DEVICE_REQUEST_GROUP_PERMISSION,
  DEVICE_GROUP_PERMISSION2,
  JOB_GROUP_PERMISSION,
  MAINTAIN_REQUEST_GROUP_PERMISSION,
  MAINTENANCE_ATTRIBUTE_GROUP_PERMISSION,
  MAINTENANCE_TEAM_GROUP_PERMISSION,
  PLAN_GROUP_PERMISSION,
  DEVICE_STATUS_GROUP_PERMISSION,
  SUPPLY_GROUP_GROUP_PERMISSION,
  SUPPLY_GROUP_PERMISSION2,
  WARNING_GROUP_PERMISSION
]

export const INSERT_PERMISSION = {
  permission: PERMISSION,
  groupPermission: GROUP_PERMISSION,
};
